name: Run Tests on Commit

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: gradle

      - name: Setup Environment Variables
        run: |
          echo "SPRING_DATASOURCE_URL=${{ secrets.DB_URL }}" > .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env

      - name: Grant Execute Permissions for Gradle
        run: chmod +x gradlew

      - name: Build and Run Tests
        run: ./gradlew test
